version: 1
disable_existing_loggers: False
formatters:
  src:
    format: '[%(asctime)s] [%(name)s] [%(levelname)s] - %(message)s'
  default:
    format: '[%(asctime)s] [%(name)s] [%(levelname)s] - %(message)s'
handlers:
  src:
    formatter: src
    class: logging.StreamHandler
    stream: ext://sys.stdout
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  src:
    level: INFO
    handlers:
      - src
    propagate: no
  aiogram:
    level: INFO
    handlers:
      - default
    propagate: no
